logging:
  level:
    root: WARN
    org:
      springframework:
        security: WARN
      hibernate:
        cache: WARN
  file:
    name: org.example.log
    path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airlinedata
    username: postgres
    password: 586910
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        javax.cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  liquibase:
    enabled: true

token:
  signing:
    key: ADF9234KADF9AF96A52KJ2G4OAGF93HL5M5XDF3468LH30